### ISSUE TITLE
Not compatible with chef 13 and the ntp cookbook

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/apparmor#17]
We want to go to chef 13, but we can't use this cookbook along side the ntp cookbook since they have resources with the same name

```

Deprecated features used!
  Cloning resource attributes for service[apparmor] from prior resource
Previous service[apparmor]: /var/chef/cache/cookbooks/ntp/recipes/apparmor.rb:20:in `from_file'
Current  service[apparmor]: /var/chef/cache/cookbooks/apparmor/recipes/default.rb:30:in `from_file' at 1 location:
    - /var/chef/cache/cookbooks/apparmor/recipes/default.rb:30:in `from_file'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```

**Comment by tas50** [comment]
This is actually a false positive and it'll work just fine in Chef 13+
